version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=Europe/Brussels
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/data/tvshows:/data/tvshows
      - /srv/jellyfin/data/movies:/data/movies
      - /srv/jellyfin/data/anime:/data/anime
      - /srv/jellyfin/data/media:/data/media
    ports:
      - 8096:8096
      - 8920:8920 #https
    restart: unless-stopped
