version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=Europe/Brussels
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/data/:/data/
    ports:
      - 8096:8096
    restart: unless-stopped
